/*
** RECALCULO DOS REGISTROS 
*/

SET TERM ^ ;

CREATE PROCEDURE RECALCULO (
    DATAINI DATE,
    DATAFIM DATE)
AS
  DECLARE VARIABLE CODIGO       INTEGER;
  DECLARE VARIABLE CODCONVENIO  INTEGER;
  DECLARE VARIABLE CODEXAME     INTEGER;
  DECLARE VARIABLE CODTABAMB    INTEGER;
  DECLARE VARIABLE VALOR_CH     NUMERIC(9, 4);
  DECLARE VARIABLE VALOR_FILME  NUMERIC(9, 4);
  DECLARE VARIABLE QTDE_CH      NUMERIC(9, 4);
  DECLARE VARIABLE QTDE_FILME   NUMERIC(9, 4);
  DECLARE VARIABLE MATERIAL     NUMERIC(9, 4);
BEGIN

  FOR
  SELECT
    CODIGO,
    CODCONVENIO,
    CODEXAME
  FROM
    REGDIARIO
  WHERE
    CAST(DATA AS DATE) BETWEEN :DATAINI AND :DATAFIM
  INTO
    :CODIGO,
    :CODCONVENIO,
    :CODEXAME
  DO
  BEGIN

    /* DADOS VINDOS DO CONVENIO */
    SELECT
      CODTABAMB,
      VALOR_CH,
      VALOR_FILME
    FROM
      CONVENIOS
    WHERE
      CODIGO = :CODCONVENIO
    INTO
      :CODTABAMB,
      :VALOR_CH,
      :VALOR_FILME;

    /* DADOS VINDOS DO EXAME */
    SELECT
      QTDE_CH,
      QTDE_FILME,
      MATERIAL
    FROM
      ITTABAMB
    WHERE
      CODTABAMB = :CODTABAMB AND
      CODEXAME  = :CODEXAME
    INTO
      :QTDE_CH,
      :QTDE_FILME,
      :MATERIAL;

    /* ATUALIZO OS DADOS DO REGISTRO EM QUESTÃO */
    UPDATE
      REGDIARIO
    SET
      VALOR_CH    = :VALOR_CH,
      VALOR_FILME = :VALOR_FILME,
      QTDE_CH     = :QTDE_CH,
      QTDE_FILME  = :QTDE_FILME,
      MATERIAL    = :MATERIAL
    WHERE
      CODIGO = :CODIGO;

  END

END

^

SET TERM ; ^

GRANT EXECUTE ON PROCEDURE RECALCULO TO PUBLIC;

SET TERM ^ ;

ALTER PROCEDURE RECALCULO (
    DATAINI DATE,
    DATAFIM DATE)
AS
DECLARE VARIABLE CODIGO INTEGER;
DECLARE VARIABLE CODCONVENIO INTEGER;
DECLARE VARIABLE CODEXAME INTEGER;
DECLARE VARIABLE CODTABAMB INTEGER;
DECLARE VARIABLE VALOR_CH NUMERIC(9,4);
DECLARE VARIABLE VALOR_FILME NUMERIC(9,4);
DECLARE VARIABLE QTDE_CH NUMERIC(9,4);
DECLARE VARIABLE QTDE_FILME NUMERIC(9,4);
DECLARE VARIABLE MATERIAL NUMERIC(9,4);
BEGIN

  FOR
  SELECT
    CODIGO,
    CODCONVENIO,
    CODEXAME
  FROM
    REGDIARIO
  WHERE
    TIPO = 'R' AND
    CAST(DATA AS DATE) BETWEEN :DATAINI AND :DATAFIM
  INTO
    :CODIGO,
    :CODCONVENIO,
    :CODEXAME
  DO
  BEGIN

    /* DADOS VINDOS DO CONVENIO */
    SELECT
      CODTABAMB,
      VALOR_CH,
      VALOR_FILME
    FROM
      CONVENIOS
    WHERE
      CODIGO = :CODCONVENIO
    INTO
      :CODTABAMB,
      :VALOR_CH,
      :VALOR_FILME;

    /* DADOS VINDOS DO EXAME */
    SELECT
      QTDE_CH,
      QTDE_FILME,
      MATERIAL
    FROM
      ITTABAMB
    WHERE
      CODTABAMB = :CODTABAMB AND
      CODEXAME  = :CODEXAME
    INTO
      :QTDE_CH,
      :QTDE_FILME,
      :MATERIAL;

    /* ATUALIZO OS DADOS DO REGISTRO EM QUESTÃO */
    UPDATE
      REGDIARIO
    SET
      VALOR_CH    = :VALOR_CH,
      VALOR_FILME = :VALOR_FILME,
      QTDE_CH     = :QTDE_CH,
      QTDE_FILME  = :QTDE_FILME,
      MATERIAL    = :MATERIAL
    WHERE
      CODIGO = :CODIGO;

  END

END

^

SET TERM ; ^

CREATE INDEX REGDIARIO_IDX1 ON REGDIARIO (DATA);

CREATE INDEX REGDIARIO_IDX2 ON REGDIARIO (TIPO);

CREATE INDEX EXAMES_IDX1 ON EXAMES (SETOR);

CREATE INDEX EXAMES_IDX2 ON EXAMES (CODEXAMB);

